Importe o pandas e os recursos necessários do scikit-learn para criar e avaliar um classificador KNN.


In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


Carregue o arquivo clientes_knn.csv em um DataFrame.


In [2]:
df = pd.read_csv('frutas_knn.csv')


Visualize as primeiras linhas da base e confira a quantidade de linhas e colunas.


In [3]:
print(df.head())
print(f"\nShape: {df.shape}")


   id  peso_g  diametro_cm  teor_acucar_brix  firmeza_kgf  indice_cor  \
0   1   134.6         8.14             12.63         6.95       0.808   
1   2   158.9         7.45             13.10         8.21       0.759   
2   3   153.8         7.28             11.15         6.48       0.926   
3   4   135.6         7.00             12.42         7.63       0.883   
4   5   168.6         7.33             11.05         7.92       0.897   

  classe_fruta  
0         maca  
1         maca  
2         maca  
3         maca  
4         maca  

Shape: (150, 7)


Verifique os tipos de dados, a existência de valores ausentes e a distribuição da coluna segmento.


In [4]:
print("\nTipos de dados:")
print(df.dtypes)
print("\nValores ausentes:")
print(df.isnull().sum())
print("\nDistribuição de segmento:")
print(df['classe_fruta'].value_counts())



Tipos de dados:
id                    int64
peso_g              float64
diametro_cm         float64
teor_acucar_brix    float64
firmeza_kgf         float64
indice_cor          float64
classe_fruta            str
dtype: object

Valores ausentes:
id                  0
peso_g              0
diametro_cm         0
teor_acucar_brix    0
firmeza_kgf         0
indice_cor          0
classe_fruta        0
dtype: int64

Distribuição de segmento:
classe_fruta
maca       50
laranja    50
pera       50
Name: count, dtype: int64


Defina como atributos de entrada as colunas idade, renda_mensal, compras_mes, ticket_medio, visitas_site_mes e dias_desde_ultima_compra.


In [5]:
X = df[["peso_g","diametro_cm","teor_acucar_brix","firmeza_kgf","indice_cor"]]


Defina a coluna segmento como variável-alvo e não utilize id_cliente como atributo do modelo.


In [6]:
y = df['classe_fruta']


Separe os dados em conjuntos de treino e teste, mantendo a proporção das classes.


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


Crie uma estratégia que normalize os atributos com StandardScaler antes de aplicar o KNeighborsClassifier.


In [8]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])


Teste diferentes valores ímpares de k e registre a acurácia obtida no conjunto de teste.


In [9]:
k_values = range(1, 21, 2)
accuracies = []

for k in k_values:
    pipeline.set_params(knn__n_neighbors=k)
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)
    print(f"k={k}: Acurácia = {acc:.4f}")


k=1: Acurácia = 0.7333
k=3: Acurácia = 0.8000
k=5: Acurácia = 0.8667
k=7: Acurácia = 0.9000
k=9: Acurácia = 0.9333
k=11: Acurácia = 0.9000
k=13: Acurácia = 0.8667
k=15: Acurácia = 0.8667
k=17: Acurácia = 0.9000
k=19: Acurácia = 0.9333


Identifique o melhor valor de k e treine o modelo final com esse valor.
Pode ser feito de outra forma


In [10]:
best_k = list(k_values)[accuracies.index(max(accuracies))]
print(f"\nMelhor k: {best_k} com acurácia: {max(accuracies):.4f}")

model_final = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier(n_neighbors=best_k))
])
model_final.fit(X_train, y_train)



Melhor k: 9 com acurácia: 0.9333


,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('scaler', ...), ('knn', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only exist if the last step of the pipeline is aclassifier.","ndarray[object](3,)","['laranja','maca','pera']"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0","ndarray[object](5,)","['peso_g','diametro_cm','teor_acucar_brix','firmeza_kgf','indice_cor']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,5
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True


Faça previsões para o conjunto de teste.


In [11]:
y_pred_final = model_final.predict(X_test)


Avalie o modelo usando acurácia, relatório de classificação e matriz de confusão.


In [12]:
print("\n=== Avaliação do Modelo Final ===")
print(f"Acurácia: {accuracy_score(y_test, y_pred_final):.4f}")
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred_final))
print("\nMatriz de Confusão:")
print(confusion_matrix(y_test, y_pred_final))



=== Avaliação do Modelo Final ===
Acurácia: 0.9333

Relatório de Classificação:
              precision    recall  f1-score   support

     laranja       1.00      0.80      0.89        10
        maca       1.00      1.00      1.00        10
        pera       0.83      1.00      0.91        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30


Matriz de Confusão:
[[ 8  0  2]
 [ 0 10  0]
 [ 0  0 10]]


Crie um novo cliente com os mesmos atributos e na mesma ordem usada no treinamento.


In [15]:
#novo_cliente = [[35, 5500, 8, 250, 15, 10]]
nova_fruta = pd.DataFrame(
    [[150, 7.5, 12, 7.5, 0.85]],
    columns=X_train.columns  # Usa exatamente os mesmos nomes e ordem do treino
)


Use o modelo para prever o segmento do novo cliente e exiba as probabilidades de cada classe.


In [16]:
classe_prevista = model_final.predict(nova_fruta)
probabilidades = model_final.predict_proba(nova_fruta)

print("\n=== Previsão para Novo Cliente ===")
print(f"Segmento previsto: {classe_prevista[0]}")
print(f"Probabilidades: {dict(zip(model_final.classes_, probabilidades[0]))}")



=== Previsão para Novo Cliente ===
Segmento previsto: maca
Probabilidades: {'laranja': np.float64(0.0), 'maca': np.float64(0.8888888888888888), 'pera': np.float64(0.1111111111111111)}
